---

<center> <h1>üìçüìç Variables and Data Types üìçüìç</h1> </center> 

---

---

###  üìç Variable Assignment


- When you create a variable you keep some space in memory. These memory locations are then used to store values. 



---

In [0]:
# define a variable name "a" and assign value 5 to it
a = 5

In [0]:
# print the value of variable
a

5

- To view some data on the output screen, python also has `print` function. Using `print` function we can control the view on the output screen.
- Later in the course, we will discuss what are functions in detail and see more use of this function.

---

In [0]:
print(a)

5

### üìç How variables work in Python

---

In [0]:
# Look at the following statements
a = 7
b = a
a = 3



***What will be the value of a?***


---

In [0]:
print(a)

3

In [0]:
print(b)

7

### üìç Variable naming rules


---
***Identifiers in Python***

* Like Variables, we have to define functions, classes, etc in python. Naming them helps to differentiate one entity from another.
* All these names given to these entities are known as `Identifiers`. 
* Python have some rules to define the Identifiers.  


***Rules of Writing Identifiers***

* Python is case sensitive language.
* Identifiers can be a combination of letters in lowercase (a to z) or uppercase (A to Z) or digits (0 to 9) or an underscore _. Names like myVariable, var_1 and print_this, all are valid example.
* An identifier cannot start with a digit.
* `1variable` is invalid, but `variable1` is perfectly fine.
* We cannot use special symbols like !, @, #, $, % etc. in our identifier. `_` is allowed.

* ***`Keywords` cannot be used as identifiers. `Keywords` are the reserved words in Python.***

---

***Keywords in Python***

---

* False	
* class	
* finally	
* is	
* return
* None	
* continue	
* for	
* lambda	
* try
* True, etc


---

---

***Python is case sensitive so `a` and `A` are different***

---

In [0]:
A = 4

In [0]:
print(a)
print(A)

3
4

***Rules to define variable names***

---

In [0]:
# allowed
a = 5

In [0]:
# only "_" underscore is allowed in allowed in special characters in the variable name
_a = 5

In [0]:
# other special characters are not allowed
@a=5

SyntaxError: invalid syntax (<ipython-input-11-d71cdc5ed5c5>, line 2)

In [0]:
# we can not start with variables name with a number
1a = 5

SyntaxError: invalid syntax (<ipython-input-12-c86ca84d118d>, line 2)

---


###  üìç Data types

* int
* string
* float
* bool

---

In [0]:
# INTEGER TYPE
a = 5

In [0]:
type(a)

int

In [0]:
# STRING TYPE
b = "lakshay"

In [0]:
type(b)

str

In [0]:
# FLOAT TYPE
c = 5.55

In [0]:
type(c)

float

In [0]:
# BOOLEAN TYPE
d = True

In [0]:
type(d)

bool

---

### üìç Type Conversion


***Python defines type conversion functions to directly convert one data type to another.***



---

***convert float to integer***

---

In [0]:
# age is generally in integer numbers
my_age = 26.33333
my_age = int(my_age)
my_age

26

***convert string to integer***

---

In [0]:
# if we try to add string and integer number, it will give an error
my_int = '2' + 6

TypeError: can only concatenate str (not "int") to str

In [0]:
# type conversion: string to int
my_int = int('2') + 6
my_int

8